/*
 * =====================================================================
 *
 *			XplicitNgin
 *			Copyright Xplicit Corporation, all rights reserved.
 *
 * =====================================================================
 */

#pragma once

#include "Xplicit.h"

/* XplicitNgin first universe */
#define XPLICIT_UNIVERSE_ID (1U)
#define XPLICIT_UNIVERSE_DELIM ":"
#define XPLICIT_UNIVERSE_PREFIX "XPLICIT_"

namespace Xplicit::Auth
{
	//!
	//! @class : XplicitID
	//! @purpose : Xplicit IDentifier
	//! 
	//! @brief Generated by server to recognize a peer.
	//! 
	class XPLICIT_API XplicitID final
	{
	public:
		XplicitID() = delete;

	public:
		//! notice pass the public hash here, not the private one!
		//! otherwise this will leak the private hash of the user!
		explicit XplicitID(const int32_t& universe, 
			const int32_t& hash) noexcept;

		~XplicitID() = default;

	public:
		XPLICIT_COPY_DEFAULT(XplicitID);

	public:
		//! cast XplicitID to integer
		const std::int64_t& as_int() noexcept;
		
		//! return xplicitID as string
		const String& as_string() const noexcept;

	private:
		Xplicit::String mXplicitId;

	private:
		std::int64_t mConnectionHash;
		std::int64_t mRegionId;

	};
}